### ISSUE TITLE
Invalid param types passed to strlen()

### ISSUE THREAD

**Issue by mudrd8mz** [eugenemodlo/moodle-filter_sagecell#1]
While testing the filter functionality, I got PHP warning

```
Warning: strlen() expects parameter 1 to be string, array given in filter/sagecell/filter.php on line 101
```

**Comment by ssemerikov** [comment]
Hello David,

Fixed: 
    $output=substr($sagecode[0], strlen("[sagecell]"), strlen($sagecode)-strlen("[/sagecell]"));
replaced with
    $output=substr($sagecode[0], strlen("[sagecell]"), strlen($sagecode[0])-strlen("[/sagecell]"));

Sincerely,
