### ISSUE TITLE
Check for [sagecell] presence in the text before calling preg_replace_callback()

### ISSUE THREAD

**Issue by mudrd8mz** [eugenemodlo/moodle-filter_sagecell#2]
See https://docs.moodle.org/dev/Filters#A_note_about_performance for how `strpos()` should be used prior to executing more expensive `preg_replace_callback()`.

**Comment by ssemerikov** [comment]
Hello David,

Fixed by:
        if (strpos($text, '[sagecell]') === false) {
           // Performance shortcut - if there is no </a> tag, nothing can match.
           return $text;
        }

Sincerely,
CC
