### ISSUE TITLE
Confusing licensing information

### ISSUE THREAD

**Issue by mudrd8mz** [eugenemodlo/moodle-filter_sagecell#4]
The file `filter.php` contains the details about the Sagecell License at the top. However, the BSD license does not seem to apply to the filter code itself as the usage of the Sagecell math server APIs has its own terms of services anyway.

It might be better to use the standard boilerplate for Moodle plugins files as documented at https://docs.moodle.org/dev/Coding_style#Files and not confuse users with a license of the Sagecell server-side license.

**Comment by ssemerikov** [comment]
Hello David,

Fixed. Thanks!

Sincerely,
CC
