### ISSUE TITLE
XSS possible with the filter enabled

### ISSUE THREAD

**Issue by mudrd8mz** [eugenemodlo/moodle-filter_sagecell#5]
When the filter is enabled, any user can inject malicious Javascript code into the page. For example, when the following text is put into a forum (or anywhere, such as user's profile description), the JS code is executed

```
[sagecell]</script><script>alert('You are doomed!');[/sagecell]
```

This is unacceptable security hole in the filter.

**Comment by ssemerikov** [comment]
Hello David!

Fixed with     $output=preg_replace("/<script.*?<\/script>/", "", $output);

Sincerely,
CC
